/**
 * 规格键 → 中文显示名。
 *
 * ★ 为什么需要这个文件（v1.5 缺陷 2）：`HardwareComponent.specs` 与
 * `FactorySystem.keySpecs` 都是 `Record<string, Claim>`，键是**给程序用的稳定语义键**
 * （`lib/compare.ts` 靠键名相同来判断「两代在比同一件事」，因此键名一旦定下就不能改）。
 * 但渲染层一直把这个键直接印在 `<dt>` 上，于是中文售前工具的「官方规格」区块显示的是
 * `powerCapacityKW`、`perNodeStorageBandwidthGBs`——汇报页 §02 更是直接写着
 * `gpuCount 72 张`。键名照旧不动，只在显示层查一次表。
 *
 * ★ 四条编写纪律（新增键时照做）：
 * 1. **不写单位**。值右侧已经单独渲染 `claim.unit`，标签里再写一遍会出现「显存带宽 TB/s 22 TB/s」。
 * 2. **写口径不写猜测**。标签必须来自该键在内容包里的实际 Claim（值 / locator / note），
 *    不能望文生义——同一个键在不同组件里可能是不同层级的数字，括号里的
 *    「每托盘 / 每机架 / 每台服务器 / 每封装」就是为了把这层口径钉住。
 * 3. **一个键只有一个标签**。少数键在不同组件里语义确实不同（见下面 ⚠️ 标注的三处），
 *    这时取一个对两边都成立的中性说法，具体差异交给值旁边的 locator / note，
 *    绝不为了好看写一个只对其中一边成立的标签。
 * 4. **查不到就原样返回键名**，不抛错、不显示空——数据层可以先加键，UI 不会因此崩掉或留白；
 *    `specLabel.test.ts` 会在覆盖不全时红掉，把补标签这件事挡在合入之前。
 *
 * 显示层同时把原始键放进 `<dt title=…>`，懂行的人悬停就能对回内容包。
 */

/**
 * 325 个键 = 内容包 `components[].specs` 的 281 个 + 只出现在 `systems[].keySpecs` 的 44 个
 * （v1.6 W-A：+2 个对象存储键 capacityPB / aggregateThroughputGBs）。
 * 按字母序排列，方便和 `specLabel.test.ts` 的覆盖断言逐条对照。
 */
export const SPEC_LABELS: Record<string, string> = {
  acceleratorCount: '加速器数量（每机架）',
  aggregateBandwidthGBs: '交换芯片聚合带宽（单向口径）',
  aggregateBandwidthGbs: '网络聚合带宽（每颗 DPU）',
  aggregateBandwidthPerNodeTBs: 'NVLink 聚合带宽（每台服务器）',
  aggregateBandwidthPerRackTBs: 'NVLink 聚合带宽（每机架）',
  aggregateBandwidthTBs: 'scale-up 聚合带宽（每机架）',
  aggregateThroughputGBs: '聚合吞吐（对象存储集群合计）',
  aiFactoryOutputVsHopper: 'AI 工厂产出倍数（对比 Hopper，厂商宣称）',
  airflowDesign: '机房气流组织建议',
  analystStructuralDetail: '分析师推测的结构细节（非官方）',
  announceTimeline: '官方公布的上市时间点',
  architecture: '指令集架构',
  armMemory: 'Arm 管理节点内存',
  asicsPerRack: '交换 ASIC 数量（每机架）',
  asicsPerTray: '交换 ASIC 数量（每托盘）',
  assemblyTime: '整机装配耗时',
  attentionSpeedupVsBlackwell: 'attention 性能提升（对比 Blackwell）',
  attentionUpliftVsBlackwell: 'attention 性能提升（对比 Blackwell，厂商宣称）',
  availability: '上市时间',
  backplaneConnector: '背板连接器型号',
  bandwidthGbs: '单端口速率',
  bandwidthPerGpuTBs: '显存带宽（每 GPU）',
  bandwidthPerPackageTBs: '显存带宽（每封装）',
  bandwidthPerRackTBs: '显存带宽（每机架合计）',
  bandwidthTbs: '光模块带宽',
  bluefield3PerTray: 'BlueField-3 DPU 数量（每托盘）',
  bluefield4PerTray: 'BlueField-4 DPU 数量（每托盘）',
  boardsPerTray: '网卡板数量（每托盘）',
  bootDriveTB: '启动盘容量',
  buswayRatedCurrentA: '母线槽 / 列头柜额定电流',
  c2cAggregateBandwidthTBs: 'NVLink-C2C 聚合带宽（每机架）',
  c2cBandwidthGBs: 'NVLink-C2C 带宽（CPU ↔ GPU）',
  c2cInterconnect: 'CPU 与 GPU 的互连方式',
  c2cLinkCount: 'C2C 链路条数（每颗芯片）',
  c2cLinkGbps: '单条 C2C 链路速率',
  c2cScope: 'C2C 直连的作用范围',
  cableCartridgeCount: '脊柱线缆匣数量（每机架）',
  cableCount: '脊柱/背板内铜缆根数',
  cableFree: '无线缆盲插设计（托盘级）',
  capacityPB: '容量（对象存储集群合计）',
  capacityPerDriveTB: '单盘容量',
  capacityPerGpuGB: '显存容量（每 GPU）',
  capacityTB: '容量',
  chassisHeightU: '机箱高度',
  chipsPerBaseboard: 'NVSwitch 芯片数量（每块基板）',
  codename: '代号',
  componentCount: '整机元器件总数',
  computeTrayCount: '计算托盘数量（每机架）',
  connectorGeneration: '连接器代际',
  connectx8PerTray: 'ConnectX-8 网卡数量（每托盘）',
  connectx9PerTray: 'ConnectX-9 网卡数量（每托盘）',
  coolantSupplyTempC: '进液温度',
  coolingCapacityKW: '冷量',
  coolingMode: '散热方式',
  coreCount: 'CPU 核数',
  coresPerCpu: 'CPU 核数（每颗）',
  coresPerTray: 'CPU 核数（每托盘合计）',
  countPerServer: '数量（每台服务器）',
  countPerTray: '数量（每托盘）',
  coveredDevices: '冷板覆盖的发热器件',
  cpoExternalLaserSource: 'CPO 外置激光源模块',
  cpoMounting: 'CPO 光引擎的安装方式',
  cpu: 'CPU 型号与配置',
  cpuBaseClockGHz: 'CPU 基频下限',
  cpuCoreCount: 'CPU 核数（每机架合计）',
  cpuCores: '内嵌 CPU 核数',
  cpuCoresPerSocket: 'CPU 核数下限（每插槽）',
  cpuCount: 'CPU 数量',
  cpuMemoryTB: 'CPU 内存容量（每机架合计）',
  cpuModel: 'CPU 型号',
  cpuPairing: '与 CPU 的配对关系',
  cpuSocketCount: 'CPU 插槽总数（全系统）',
  cpuSockets: 'CPU 插槽数（每台服务器）',
  cpusPerTray: 'CPU 数量（每托盘）',
  currentA: '额定电流',
  ddr5TotalTB: 'DDR5 内存总容量（每机架）',
  delayOutlook: '延期风险（媒体报道）',
  denseFp4UpliftVsBlackwell: 'FP4 稠密算力提升（对比 Blackwell，厂商宣称）',
  diesPerPackage: 'die 数量（每封装）',
  distributionForm: '配电形态',
  distributionVoltageV: '机房配电电压等级',
  domainScope: 'NVLink 域的范围',
  dpu: 'DPU 型号与配置',
  dpusPerServer: 'DPU 数量（每台服务器）',
  dramViaFabricGB: '经托盘扩展逻辑挂载的 DRAM 容量',
  dramViaHostGB: '经主机 CPU 挂载的 DRAM 容量',
  driveCountPerServer: '数据盘数量（每台服务器）',
  dualPlaneSplit: '双平面拆分方式',
  elevationScaleU: '机架立面图的 U 刻度上限',
  ethernetGeneration: '以太网交换代际',
  exampleNodeCount: '参考配置的节点数',
  executionModel: '执行模型',
  executionModules: '执行单元构成',
  existenceAndMedium: '互连的存在性与介质（官方确认）',
  fastMemoryPerTrayTB: '快速内存容量（每托盘）',
  fastMemoryTB: '快速内存总容量（每机架）',
  feedsInRackSwitches: '是否为机架内交换机供电',
  fieldReplaceability: '现场可更换性',
  firstToMarket: '预计率先量产的版本',
  flowRateLpm: '歧管流量',
  formFactor: '形态',
  formFactorName: '机架形态代号（本项目建模口径，非官方）',
  foundryNode: '制程节点',
  fp4DensePflops: 'FP4 稠密算力（系统合计）',
  fp4DensePflopsPerPackage: 'FP4 稠密算力（每封装）',
  fp4DenseTflops: 'FP4 稠密算力（单卡）',
  fp4DenseTflopsPerGpu: 'FP4 稠密算力（单卡）',
  fp4InferencePflops: 'FP4 推理算力（每机架）',
  fp4SparsePflops: 'FP4 算力（含稀疏，整板）',
  fp8DensePflops: 'FP8 稠密算力（每机架）',
  fp8DensePflopsPerPackage: 'FP8 稠密算力（每封装）',
  fp8DenseTflops: 'FP8 稠密算力（单卡）',
  fp8PerTrayPflops: 'FP8 推理算力（每托盘）',
  fp8Pflops: 'FP8 推理算力（每机架）',
  fp8PflopsPerTray: 'FP8 推理算力（每托盘）',
  fp8RackPflops: 'FP8 推理算力（每机架）',
  fp8SparsePflops: 'FP8 算力（含稀疏）',
  generation: '代际',
  generationalBandwidthPerGpu: '显存带宽的世代对照（H200 → B200 → B300）',
  generationalMemoryPerGpu: '显存容量的世代对照（H200 → B200 → B300）',
  gpuCount: 'GPU 数量',
  gpuDensityGain: '同功率包络下的 GPU 数量增幅',
  gpuDieCount: 'GPU die 总数（分析师口径）',
  gpuMemoryBandwidthPerNodeTBs: '显存带宽（每台服务器合计）',
  gpuMemoryBandwidthTBs: '显存带宽（每机架合计）',
  gpuMemoryPerNodeTB: '显存容量（每台服务器合计）',
  gpuMemoryTotalTB: '显存容量（每机架合计）',
  gpuToGpuBandwidthGBs: 'GPU 之间的 NVLink 带宽',
  gpuToNicRatio: 'GPU 与网卡的配比',
  gpusPerBaseboard: 'GPU 数量（每块基板）',
  gpusPerTray: 'GPU 数量（每托盘）',
  groqRelationship: '与 Groq 的技术许可关系',
  hbmBandwidthTBs: '显存带宽（单卡）',
  hbmPerGpuGB: '显存容量（每 GPU）',
  hbmPerGpuRaGB: '显存容量（每 GPU，参考架构口径）',
  hbmStackConfig: 'HBM 堆栈与控制器配置',
  hbmStacks: 'HBM 堆栈数量',
  heightU: '机架高度',
  hostCpusPerTray: '主机 CPU 数量（每托盘）',
  hostGpuInterconnect: '主机与 GPU 的互连方式',
  hpcCapacityPerSocketTB: 'HPC 场景本地盘容量下限（每 CPU 插槽）',
  hpmPcbLayers: 'HPM 板 PCB 层数',
  inferenceCapacityPerSocketTB: '推理场景本地盘容量下限（每 CPU 插槽）',
  inlineCryptoGbs: '线速加密吞吐',
  inputVoltage: '输入电压',
  interRackTopology: '跨机架拓扑',
  interface: '接口形态',
  kvCacheOffloadNote: 'KV cache 卸载的官方提示',
  laneSpeed: '单通道速率',
  latency: '时延口径',
  leafSpineSplit32Node: '32 节点设计点的 leaf / spine 配比',
  leakDetection: '液体泄漏检测',
  linkSpec: '链路规格',
  linksFromEachGpu: '每张 GPU 到单颗交换芯片的链路条数',
  liquidCooled: '是否液冷',
  liquidCooling: '是否液冷',
  localStoragePolicy: '本地存储配置要求',
  localStorageTB: '本地存储容量',
  lpddr5PerTrayTB: 'LPDDR5 内存容量（每托盘合计）',
  lpuCount: 'LPU 数量（每机架）',
  lpuTrayCount: 'LPU 计算托盘数量（每机架）',
  lpusPerTray: 'LPU 数量（每托盘）',
  mainstreamTdpKW: '主流版本 TDP（分析师预期）',
  // ⚠️ 一键两义：组件侧是「集群最多支持几个管理节点」（8 个），
  //    系统 keySpecs 侧是「参考架构最多支持几台 HGX 服务器」（128 台）。取中性说法。
  maxNodes: '节点数上限（参考架构口径）',
  maxModelPerGpuB: '单卡可承载的模型规模上限',
  maxScalableUnits: '可扩展单元（SU）数量上限',
  maxTrayDistanceU: '背板上托盘之间的最大距离',
  medium: '互连介质',
  memoryBandwidthGBs: '板载内存带宽',
  // ⚠️ GPU 上是显存带宽、CPU 上是主存带宽——同一个键在两类组件上都用，取合并说法。
  memoryBandwidthTBs: '内存带宽（GPU 上即显存带宽）',
  memoryHierarchy: '存储层次',
  memoryPerPackageGB: '显存容量（每封装）',
  memoryTechnology: '存储技术路线',
  memoryType: '显存类型',
  mgxGeneration: 'MGX 机架代际',
  migInstances: 'MIG 实例数上限',
  minBaseClockGHz: 'CPU 基频下限',
  minComputeBandwidthGBs: '计算网带宽下限（每节点）',
  minCoresPerSocket: 'CPU 核数下限（每插槽）',
  minMemoryBandwidthGBs: '系统内存带宽下限',
  minSystemMemoryTB: '系统内存容量下限',
  model: '型号',
  modelNameConflict: '型号：官方两种写法并存',
  moduleFormFactor: '光模块形态（NPO / CPO）',
  mounting: '安装位置',
  mountingPlace: '安装位置',
  namingHistory: '命名沿革（官方改名留痕）',
  networkOs: '网络操作系统',
  networkPortSpeedGbE: '网口速率',
  nicCountPerNode: '网卡数量（每台服务器）',
  nics: '网卡配置',
  nicsPerBaseboard: '网卡数量（每块基板）',
  nicsPerBoard: '网卡芯片数量（每块网卡板）',
  nicsPerTray: '网卡数量（每托盘）',
  nodeArchitectureCode: '节点架构口诀（CPU-GPU-网卡-每 GPU 带宽）',
  nodeConfiguration: '节点配置口诀（CPU-GPU-网卡-每 GPU 带宽）',
  nodeCount: '管理节点数量',
  nodesPerScalableUnit: '每个可扩展单元（SU）的服务器台数',
  npoMounting: 'NPO 模块的安装方式',
  nvfp4PerTrayPflops: 'NVFP4 算力（每托盘，未标注稠密 / 稀疏）',
  nvlinkAggregateBandwidthTBs: 'NVLink 聚合带宽（域内合计）',
  nvlinkAggregateTBs: 'NVLink 聚合带宽（每块基板）',
  nvlinkDomainOptions: '官方给出的 NVLink 域档位',
  nvlinkGeneration: 'NVLink 代际',
  nvlinkLinksPerGpu: 'NVLink 链路条数（每 GPU）',
  nvlinkPerGpuGBs: 'NVLink 带宽（每 GPU）',
  nvlinkPerGpuTBs: 'NVLink 带宽（每 GPU）',
  nvlinkPerGpuUnidirectionalGBs: 'NVLink 带宽（每 GPU，单向口径）',
  nvlinkPerTrayTBs: 'NVLink 带宽（每托盘）',
  nvlinkScaleUp: 'scale-up 接入方式',
  nvswitchChipCount: 'NVSwitch 芯片数量（每块基板）',
  nvswitchTrayCount: 'NVLink 交换托盘数量（每机架）',
  offloads: '硬件卸载能力',
  oobPortGbs: '带外管理口速率',
  oobPortsPerServer: '带外管理口数量（每台服务器）',
  operatingMode: '工作模式',
  opticalEnginesCpo: 'CPO 光引擎数量（每颗交换 ASIC）',
  opticsVariants: '光互连版本（NPO / CPO）',
  packageConfiguration: '封装内的 die 构成',
  packaging: '封装工艺',
  pairedThroughputGain: '配对后的吞吐提升（厂商宣称）',
  pairing: '配对工作方式',
  pcieGen: 'PCIe 代际与通道数',
  pcieInterface: 'PCIe 接口规格',
  pcieToHost: '基板到主机的 PCIe 链路',
  pcieTopologyRequirement: 'PCIe 拓扑要求',
  pduCapacityKW: 'PDU 容量',
  pduCount: 'PDU 路数',
  perGpuBandwidthTBs: '每 GPU 的 scale-up 带宽',
  perGpuBandwidthTbs: '每 GPU 的 scale-out 网络带宽',
  perGpuLinkBandwidthGBs: '经 NVSwitch 的 GPU 间带宽',
  perGpuNetworkGbs: '每 GPU 的对外网络带宽',
  perNodeStorageBandwidthGBs: '存储带宽上限（每计算节点）',
  perStackCapacityGB: '单个 HBM 堆栈容量',
  portCount: '端口数',
  portSpeedGbs: '单端口速率',
  portType: '端口形态',
  ports: '端口数',
  powerCapacityKW: '机房总供电容量',
  powerFeatures: '供电特性',
  powerRedundancy: '供电冗余要求',
  presence: '部件存在性',
  processNode: '制程节点',
  prototypeCodename: '原型机代号',
  psuPowerKW: '单个电源模块功率',
  psusPerShelf: '电源模块数量（每个电源架）',
  rackCount: '机架数量（组成单一域）',
  rackFamily: '机架系列',
  rackPowerKW: '整机架功率',
  rackType: '机架类型',
  recommendedComputeBandwidthGBs: '计算网带宽推荐值（每节点）',
  recommendedCoresPerSocket: 'CPU 核数推荐值（每插槽）',
  redundancy: '冗余等级',
  redundancyMode: '冗余模式',
  redundancyRequirement: '冗余要求',
  remoteManagement: '远程管理接口',
  returnWaterTempC: '一次侧回水温度',
  role: '承担的角色',
  roles: '承担的角色',
  scaleOutBandwidthTBs: 'scale-out 网络带宽（每机架合计）',
  scaleOutNic: 'scale-out 网卡',
  scaleUpBandwidthPerTrayTBs: 'scale-up 带宽（每托盘）',
  // ⚠️ 一键两义：组件侧是单颗 LPU 的 2.5 TB/s，系统 keySpecs 侧是整机架的 640 TB/s。
  scaleUpBandwidthTBs: 'scale-up 带宽',
  scaleUpTopology: 'scale-up 拓扑',
  serdes: 'SerDes 规格',
  serdesSpeed: 'SerDes 速率',
  serverPowerKW: '整机功率（每台服务器）',
  serversPerRack: '服务器台数（每机架）',
  sfp28Ports: 'SFP28 端口数',
  sharedHeightAcrossVariants: '两种版本的机架高度是否相同',
  sharpFp8Tflops: 'SHARP 网内计算算力（FP8）',
  shelfHeightU: '电源架高度',
  shelfPowerKW: '单个电源架输出功率',
  shelvesPerRack: '电源架数量（每机架）',
  siliconGeneration: '交换芯片代际',
  singlePlaneOption: '单平面组网选项',
  smCount: 'SM（流多处理器）数量',
  socammPlacement: 'SOCAMM 内存条摆位',
  socketsPerServer: 'CPU 插槽数（每台服务器）',
  sramBandwidthPBs: '片上 SRAM 带宽（每机架合计）',
  sramBandwidthPerTrayPBs: '片上 SRAM 带宽（每托盘）',
  sramBandwidthTBs: '片上 SRAM 带宽（单颗）',
  sramPerChipMB: '片上 SRAM 容量（单颗）',
  sramPerTrayGB: '片上 SRAM 容量（每托盘）',
  sramTotalGB: '片上 SRAM 总容量（每机架）',
  stackHeight: 'HBM 堆栈层数',
  stacksPerGpu: 'HBM 堆栈数量（每 GPU）',
  superNicsPerBaseboard: 'SuperNIC 数量（每块基板）',
  superchipsPerTray: '超级芯片数量（每托盘）',
  supplyAirTempC: '送风温度',
  supplyWaterTempC: '二次侧供水温度',
  switchCount32Node: '32 节点设计点的交换机台数',
  switchCountBySu: '交换机台数（按 SU 规模）',
  switchesPerRack: '交换机台数（每机架）',
  switchless: '有无交换层',
  systemMemoryGB: '系统内存容量',
  systemMemoryTB: '系统内存容量',
  tdpW: 'TDP（单颗热设计功耗）',
  threadsPerCpu: '线程数（每颗 CPU）',
  topology: '网络拓扑',
  topologyDetail: '拓扑细节',
  topologyName: '拓扑名称（分析师归类）',
  topologyNameOfficial: '拓扑名称（官方点名）',
  totalBusWidthBits: '显存总位宽',
  totalChipCount: '芯片总数（含 HBM）',
  totalPerPackageGB: '显存容量（每封装合计）',
  totalPerRackTB: '显存容量（每机架合计）',
  trainingCapacityPerSocketTB: '训练场景本地盘容量下限（每 CPU 插槽）',
  transistorCountB: '晶体管数量',
  transistorsB: '晶体管数量',
  trayAggregateBandwidthGbs: '计算网聚合带宽（每托盘）',
  trayBandwidthTBs: '托盘总带宽',
  trayCount: '计算托盘数量（每机架）',
  trayFrontElements: '托盘正面的接口构成',
  trayHeightU: '托盘高度',
  trayLayout: '机架内的托盘排布',
  trayPowerW: '单托盘功耗',
  traysPerRack: '托盘数量（每机架）',
  unitCount: '设备台数',
  universalRack: '通用机架复用',
  vectorWidthBytes: '向量工作单元宽度',
  vendorModel: '厂商物料型号',
  vendorPart: '厂商型号',
  voltageV: '电压等级',
  vsPreviousGen: '相对上一代的提升',
  weightKg: '整机重量',
  x86Memory: 'x86 管理节点内存',
  year: '所属年份（分析师路线图）',
}

/**
 * 规格键的显示名。查不到时**原样返回键名**——数据层可以先加键、UI 不会崩也不会留白，
 * 缺标签这件事由 `specLabel.test.ts` 的覆盖断言在合入前拦下。
 */
export function specLabel(key: string): string {
  return SPEC_LABELS[key] ?? key
}

/** 该键是否已经有中文标签（UI 用它决定 `<dt>` 要不要保留等宽字体的「键名感」）。 */
export function hasSpecLabel(key: string): boolean {
  return key in SPEC_LABELS
}
