import { expect, test } from '@playwright/test'
import { DEFAULT_SCENARIO, encodeScenario } from '../../src/lib/scenario'

test.beforeEach(async ({}, info) => test.skip(info.project.name !== 'desktop', 'Explicit viewport coverage'))

test('交互提升：编辑时结果保持可见，预设与自定义状态有明确反馈', async ({ page }) => {
  await page.goto('/?gl=off&motion=off')
  await page.locator('[data-right-tab="capacity"]').click()
  const panel = page.locator('[data-capacity-panel]')
  const feedback = panel.locator('[data-capacity-feedback]')
  await expect(feedback).toBeInViewport()
  await expect(panel.getByRole('button', { name: '中', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const initial = await feedback.locator('[data-feedback-throughput]').textContent()
  await panel.getByLabel('机架数', { exact: true }).fill('2')
  await expect(feedback.locator('[data-feedback-throughput]')).not.toHaveText(initial!)
  await panel.getByLabel('每副本 batch', { exact: true }).fill('17')
  await expect(panel.locator('[data-scenario-input]')).toContainText('自定义')
  await panel.getByLabel('Rubin 规格配置', { exact: true }).scrollIntoViewIfNeeded()
  await expect(feedback).toBeInViewport()
  await expect(page).toHaveScreenshot('capacity-live-feedback.png')
})

for (const width of [390, 900]) {
  test(`交互提升：${width}px 播放控制与模型同时可见，无抽屉遮挡`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/?gl=off&motion=off')
    await page.getByRole('button', { name: '流程与负载', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '流程与负载', exact: true })
    await dialog.getByRole('button', { name: '负载演示', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    const controls = page.locator('[data-mobile-load-inline]')
    await expect(controls.getByRole('button', { name: '播放演示', exact: true })).toBeInViewport()
    await expect(page.locator('[data-fallback-2d]')).toBeInViewport()
    await expect(controls.locator('[data-generated-tokens]')).toBeInViewport()
    await controls.getByRole('button', { name: '下一个 token', exact: true }).click()
    await expect(controls.locator('[data-generated-tokens]')).toContainText('1 / 256')
    await controls.getByRole('button', { name: '上一个 token', exact: true }).click()
    await expect(controls.locator('[data-generated-tokens]')).toContainText('0 / 256')
    const part = page.getByRole('button', {name:'查看 计算托盘', exact:true})
    await part.click()
    const detail = page.getByRole('dialog', {name:'部件详情', exact:true})
    await expect(detail).toContainText('计算托盘')
    await page.keyboard.press('Escape')
    await expect(part).toBeFocused()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page).toHaveScreenshot(`load-inline-${width}.png`)
  })
}

test('交互提升：逐 token 回看与键盘操作可逆，计算结果不受演示节奏影响', async ({ page }) => {
  const input = { ...DEFAULT_SCENARIO, outputTokens: 8, inputTokens: 16, batch: 2 }
  await page.goto(`/?gl=off&motion=off&simulation=load&scenario=${encodeURIComponent(encodeScenario(input))}`)
  const controls = page.locator('[data-simulation-phase]')
  await controls.focus()
  await page.keyboard.press('ArrowRight')
  await expect(controls.locator('[data-generated-tokens]')).toContainText('1 / 8')
  const firstKV = await controls.locator('[data-simulation-kv]').textContent()
  await page.keyboard.press('ArrowRight')
  await expect(controls.locator('[data-generated-tokens]')).toContainText('2 / 8')
  await page.keyboard.press('ArrowLeft')
  await expect(controls.locator('[data-simulation-kv]')).toHaveText(firstKV!)
  const max = await page.getByLabel('计算进度', { exact: true }).getAttribute('max')
  await page.getByLabel('演示播放速度', { exact: true }).selectOption('4')
  await controls.focus()
  await page.keyboard.press('End')
  await expect(controls).toHaveAttribute('data-simulation-phase', 'complete')
  expect(Number(await page.getByLabel('计算进度', { exact: true }).inputValue())).toBeCloseTo(Number(max), 9)
  await page.keyboard.press('Home')
  await expect(controls.locator('[data-generated-tokens]')).toContainText('0 / 8')
  // The resource summary must not cover the 2D tabs.
  await page.getByRole('tab', {name:'组件树', exact:true}).click()
  await expect(page.getByRole('tab', {name:'组件树', exact:true})).toHaveAttribute('aria-selected','true')
  await page.getByRole('tab', {name:'结构图', exact:true}).click()
  await expect(page).toHaveScreenshot('load-overview.png')
})

test('交互提升：负载驱动可见粒子，暂停与减少动态效果生效且不夺取相机', async ({ page }) => {
  // A long prefill keeps a physical path selected while sampling particle movement.
  const input = { ...DEFAULT_SCENARIO, inputTokens: 32768, cachedTokens: 0, outputTokens: 64, batch: 64 }
  await page.goto(`/?focus=asm.gb300.compute-tray&level=board&simulation=load&scenario=${encodeURIComponent(encodeScenario(input))}`)
  await page.locator('[data-ready="1"]').waitFor()
  const canvas = page.locator('canvas').first()
  await expect(canvas).toHaveAttribute('data-flow-particle-phase', /\d/)
  // Consume any reduced-motion preference persisted by a preceding local visit.
  await page.getByLabel('演示播放速度', { exact: true }).selectOption('0.25')
  const pose = await canvas.getAttribute('data-camera-pose')
  const phase = await canvas.getAttribute('data-flow-particle-phase')
  await page.getByRole('button', { name: '播放演示', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-flow-particles-visible', '1')
  await expect.poll(() => canvas.getAttribute('data-flow-particle-phase')).not.toBe(phase)
  await page.getByRole('button', { name: '暂停演示', exact: true }).click()
  const paused = await canvas.getAttribute('data-flow-particle-phase')
  await page.waitForTimeout(300)
  await expect(canvas).toHaveAttribute('data-flow-particle-phase', paused!)
  await expect(canvas).toHaveAttribute('data-camera-pose', pose!)
  await page.goto(`/?motion=off&focus=asm.gb300.compute-tray&level=board&simulation=load&scenario=${encodeURIComponent(encodeScenario(input))}`)
  await page.locator('[data-ready="1"]').waitFor()
  await page.getByRole('button', { name: '播放演示', exact: true }).click()
  await expect(canvas).toHaveAttribute('data-flow-particles-visible', '0')
  await expect.poll(() => page.getByLabel('计算进度', { exact: true }).inputValue()).not.toBe('0')
})
