import { expect, test } from '@playwright/test'
import { DEFAULT_SCENARIO, encodeScenario } from '../../src/lib/scenario'

test.beforeEach(async({},info)=>test.skip(info.project.name!=='desktop','Explicit viewport coverage in one project'))
for(const width of [390,768,900,1024,1280,1440]) {
  test(`场景 · ${width}px 可编辑、抽屉键盘、无横向溢出`,async({page})=>{
    await page.setViewportSize({width,height:900})
    await page.goto('/?gl=off&motion=off')
    await page.locator('[data-ready="1"]').waitFor()
    if(width<1200) await page.getByRole('button',{name:'产能与场景',exact:true}).click()
    else await page.locator('[data-right-tab="capacity"]').click()
    const panel=page.locator('[data-capacity-panel]').first()
    await panel.getByLabel('每副本 batch',{exact:true}).fill('17')
    await panel.getByLabel('输出 tokens',{exact:true}).fill('333')
    if(width<1200) {
      const dialog=page.getByRole('dialog',{name:'产能与场景',exact:true})
      await expect(dialog).toBeVisible()
      await dialog.getByRole('button',{name:'关闭',exact:true}).focus()
      await page.keyboard.press('Shift+Tab')
      expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true)
      await page.keyboard.press('Escape')
      await expect(dialog).toHaveCount(0)
      await expect(page.getByRole('button',{name:'产能与场景',exact:true})).toBeFocused()
      await page.getByRole('button',{name:'产能与场景',exact:true}).click()
    } else {
      await page.locator('[data-right-tab="detail"]').click()
      await page.locator('[data-right-tab="capacity"]').click()
    }
    await expect(panel.getByLabel('每副本 batch',{exact:true})).toHaveValue('17')
    await expect(panel.getByLabel('输出 tokens',{exact:true})).toHaveValue('333')
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  })
}

test('场景 · 分享、比较、报告往返保留输入和配置版本',async({page})=>{
  const input={...DEFAULT_SCENARIO,modelId:'qwen3-235b',batch:13,unitCount:2,outputTokens:123,hardwareProfile:'datasheet' as const}
  await page.goto(`/?gl=off&motion=off&gen=sys.hgx-b300&scenario=${encodeURIComponent(encodeScenario(input))}`)
  await page.locator('[data-right-tab="capacity"]').click()
  await expect(page.getByLabel('每副本 batch',{exact:true})).toHaveValue('13')
  await page.getByRole('button',{name:'负载演示',exact:true}).click()
  await page.getByRole('button',{name:'分享场景',exact:true}).click()
  const url=await page.getByLabel('场景链接',{exact:true}).inputValue()
  await page.getByRole('button',{name:'比较',exact:true}).click()
  await page.locator('[data-capacity-panel] > details > summary').click()
  await expect(page.getByLabel('每副本 batch',{exact:true})).toHaveValue('13')
  await page.getByRole('link',{name:'汇报页 →'}).click()
  await expect(page.locator('[data-report-capacity]').first()).toContainText('qwen3-235b')
  await page.reload()
  await expect(page.locator('[data-report-capacity]').first()).toContainText('qwen3-235b')
  await expect(page.locator('[data-claim-audit]')).toBeVisible()
  await page.goto(url)
  await page.locator('[data-right-tab="capacity"]').click()
  await expect(page.getByLabel('每副本 batch',{exact:true})).toHaveValue('13')
  await expect(page.getByLabel('Rubin 规格配置',{exact:true})).toHaveValue('datasheet')
  await expect(page.locator('[data-simulation-phase]')).toHaveAttribute('data-simulation-phase','prefill')
})

test('负载 · 2D / 减少动态效果也推进，输出结束一致且不移动视角',async({page})=>{
  const input={...DEFAULT_SCENARIO,outputTokens:8,batch:2,inputTokens:8,cachedTokens:0}
  await page.goto(`/?gl=off&motion=off&scenario=${encodeURIComponent(encodeScenario(input))}`)
  await page.getByRole('button',{name:'负载演示',exact:true}).click()
  await page.getByRole('button',{name:'播放演示',exact:true}).click()
  await expect(page.locator('[data-simulation-phase]')).toHaveAttribute('data-simulation-phase','complete')
  await expect(page.locator('[data-generated-tokens]')).toContainText('8 / 8')
  await page.getByRole('button',{name:'从头演示',exact:true}).click()
  await page.getByLabel('演示播放速度',{exact:true}).selectOption('4')
  await page.getByRole('button',{name:'播放演示',exact:true}).click()
  await expect(page.locator('[data-simulation-phase]')).toHaveAttribute('data-simulation-phase','complete')
  await expect(page.locator('[data-generated-tokens]')).toContainText('8 / 8')
  await expect(page.locator('[data-simulation-resources]')).toContainText('模拟参与')
  await page.getByRole('button',{name:'流程讲解',exact:true}).click()
  await expect(page.locator('footer[data-flow-step]')).toHaveAttribute('data-flow-step','14')
  await page.getByRole('button',{name:'负载演示',exact:true}).click()
  await page.getByRole('button',{name:'从头演示',exact:true}).click()
  await page.getByRole('button',{name:'下一个 token',exact:true}).click()
  await expect(page.locator('[data-generated-tokens]')).toContainText('1 / 8')
  await page.getByRole('button',{name:'流程讲解',exact:true}).click()
  await expect(page.locator('footer[data-flow-step]')).toHaveAttribute('data-flow-step','8')
})

test('上下文上限与未知计算精度在 UI 拒绝',async({page})=>{
  await page.goto('/?gl=off&motion=off')
  await page.locator('[data-right-tab="capacity"]').click()
  const panel=page.locator('[data-capacity-panel]')
  await panel.getByLabel('模型',{exact:true}).selectOption('llama3-70b')
  await panel.getByLabel('输入 tokens',{exact:true}).fill('8192')
  await expect(panel.getByRole('alert')).toContainText('8192 token 上限')
  await expect(panel.locator('[data-capacity-card]')).toHaveAttribute('data-capacity-kind','refused')
  await panel.getByRole('button',{name:'重置场景',exact:true}).click()
  await panel.getByLabel('计算精度',{exact:true}).selectOption('int4')
  await expect(panel.locator('[data-capacity-card]')).toContainText('INT4 不等于 NVFP4')
})

test('所有代际都有完整的本系统流程，POD 模块可搜索',async({page})=>{
  for(const id of ['sys.gb300-nvl72','sys.hgx-b300','sys.vera-rubin-nvl72','sys.groq3-lpx','sys.rubin-ultra-nvl576']) {
    await page.goto(`/?gl=off&motion=off&gen=${id}`)
    await expect(page.locator('footer[data-flow-total]')).toHaveAttribute('data-flow-total','15')
    await page.locator('[data-flow-step-button="7"]').click()
    await expect(page.locator('footer[data-flow-step]')).toHaveAttribute('data-flow-step','7')
  }
  await page.goto('/?gl=off&gen=sys.vera-rubin-nvl72')
  await page.getByRole('searchbox',{name:'搜索组件'}).fill('STX')
  await expect(page.getByRole('button',{name:'BlueField-4 STX / CMX · KV 存储',exact:true}).first()).toBeVisible()
})

test('窄屏组件搜索打开详情，嵌套抽屉 Escape 按层关闭并恢复焦点',async({page})=>{
  await page.setViewportSize({width:900,height:900})
  await page.goto('/?gl=off&gen=sys.vera-rubin-nvl72')
  await page.getByRole('button',{name:'组件与导览',exact:true}).click()
  const nav=page.getByRole('dialog',{name:'组件与导览',exact:true})
  await nav.getByRole('searchbox',{name:'搜索组件'}).fill('STX')
  const result=nav.getByRole('button',{name:'BlueField-4 STX / CMX · KV 存储',exact:true})
  await result.click()
  const detail=page.getByRole('dialog',{name:'部件详情',exact:true})
  await expect(detail).toContainText('Dual STX')
  await page.keyboard.press('Escape')
  await expect(detail).toHaveCount(0);await expect(nav).toBeVisible()
  await expect(result).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(nav).toHaveCount(0)
  await expect(page.getByRole('button',{name:'组件与导览',exact:true})).toBeFocused()
})

test('390px 报告与展开核验表无页面溢出，差异表支持键盘滚动',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/report')
  const audit=page.locator('[data-claim-audit]')
  await expect(audit).toContainText('当前 645 条')
  await audit.locator('summary').click()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  const table=page.getByRole('region',{name:/差异表$/}).first()
  await table.focus()
  await page.keyboard.press('ArrowRight')
  await expect.poll(()=>table.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0)
})
